name: 🏷️ Pull Request Labels

on:
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@d25134c992b943fb6ad00c25ea00eb5988c0a9dd # 5.4.2
        with:
          mode: exactly
          count: 1
          labels: "kind/image, kind/runtime, kind/distribution, kind/test, kind/cleanup, breaking change"
